console.log("Dhananjay Shinde");
let str1= " Dhananjay ";
let str2 = new String("shinde");
console.log(str1.length +" "+ str2.length);
console.log(str1.indexOf('h'));
str3 = str1.trim();
console.log(str1.length);
console.log(str3.length);
const str4 = str3.slice(-6, 6);
console.log(str4);
console.log(str1.replaceAll('a', 't'));
console.log(str1);
console.log(str1.split("a"));